apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: erfj9jd11-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: erfj9jd11-go 
  name: erfj9jd11-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: erfj9jd11-go 
